package constants


const (
    USER_INDEX = "user"
    POST_INDEX = "post"
    ES_URL = "http://YOUR_VM_INSTANCE_INTERNAL_IP:9200"
    ES_USERNAME = "YOUR_ELASTIC_SEARCH_ACOUNT"
    ES_PASSWORD = "YOUR_ELASTIC_SEARCH_PASSWORD"
    GCS_BUCKET = "YOUR_GOOGLE_CLOUD_STORAGE_BUCKET"
)
